version: '3.1'
services:
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'
  backend:
    container_name: backend
    restart: always
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - mongo
