version: '3.1'
services:
  mongo_dev:
    container_name: mongodb_dev
    restart: always
    image: mongo
    ports:
      - '27017:27017'
  backend_dev:
    container_name: backend_dev
    restart: always
    environment:
      PORT: 8000
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: nodemon index.js
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '8000:8000'
    links:
      - mongo_dev
