version: '3.1'
services:
  mongo:
    container_name: mongodb
    restart: always
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /db:/data/db
  backend:
    restart: unless-stopped
    environment:
      MONGO_URL: ${MONGO_URL}
    image: chauanphu/bhld-tgp:latest
    command: npm run start
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 8000:8000
    links:
      - mongo
  frontend:
    restart: unless-stopped
    environment:
      REACT_APP_API: ${REACT_APP_API}
    image: chauanphu/bhld-frontend:1.0.2
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  db:
