version: '3.1'
services:
  mongo:
    container_name: mongodb
    restart: always
    image: mongo
    ports:
      - '27017:27017'
  backend:
    container_name: backend
    restart: always
    environment:
      PORT: 8000
    build:
      context: .
      dockerfile: Dockerfile
    command: node index.js
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '8000:8000'
    links:
      - mongo
