version: '3.1'
services:
  mongo:
    container_name: mongodb
    restart: always
    image: mongo
    ports:
      - '27017:27017'
  backend:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - '8000:8000'
    depends_on:
      - mongo
