version: '3.1'
services:
  mongo:
    container_name: mongodb
    restart: always
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /db:/data/db
  backend:
    container_name: backend
    restart: always
    environment:
      PORT: 8000
      REACT_APP_API: https://thietbibaoho.net/api
    image: chauanphu/bhld-tgp:latest
    command: npm run start
    volumes:
      - ./:/app
    ports:
      - 80:8000
    links:
      - mongo
